export const PATIENT_DETAILS = 'Patient Details (1)'
export const NUMBER_OF_TESTS = '1 Test'
export const REPORTS_BY = 'E-Reports by 12hrs'
export const COVID_RTPCR = 'Covid RTPCR Test'
export const HOME_VISIT = 'Home Visit'
export const TEST_INCLUDED = '1 test included'
export const FREE_CONSULTATION = 'Free consultation'
export const ONLINE_REPORTS = 'Online reports'
export const STARTING_PRICE = 'Starting from $1200'
export const REPORTS_TIME = 'Reports ready in 24 Hours'
export const DESCRIPTION_1 =
  'This package covers nasal/oral swab test & same day pickup. It indicates if you currently have the COVID-19 infection.'
export const DISCLAIMER_1 =
  'Disclaimer 1:For travelling purposes, please ensure the name is as per govt ID proof.'
export const DISCLAIMER_2 =
  'Disclaimer 2: Vaccination status will be required and Covid Positive Reports will be made available as per local'
export const MUNICIPAL_GUIDELINES = 'Municipal corporation guidelines.'
export const WHY_PACKAGE = 'Why you should book this package?'
export const FEATURE_1 = 'To check if you have an active COVID-19 infection'
export const FEATURE_2 = 'If you are showing symptoms of COVID-19 infection'
export const FEATURE_3 =
  'If you had a contact with someone with confirmed COVID-19'
export const ITEM_TOTAL = 'Item Total'
export const LABEL_DISCOUNT = 'Discount'
export const LABEL_GRAND_TOTAL = 'Grand Total'
export const PRICE = '1200'
export const DISCOUNT_PRICE = '100'
export const FINAL_PRICE = '1100'
export const LAB_NAME = 'Los Altos Center Lab'
export const SLOT_SELECTED = 'Time Slot Selected'
export const CHANGE = 'Change'
export const DATE = 'Tue, Feb 23, 2022'
export const TIME = '07.00 - 08.00 AM'
export const HEADING_ADDRESS = 'Address Selected (Home)'
export const ADDRESS =
  '2235 California Street Mountain View California APT#021 - 11023'

export const BANNER_HEADLINE = '60% off on your first order'
export const BANNER_CAPTION = 'Your health is our priority'
export const BANNER_BUTTON_TEXT = 'Book Now'
